name: .NET - Get Project File ReleaseVersion
author: Dale Myszewski
description: Get the Release Version from *.csproj files in newer .Net SDK projects

inputs:
    PROJ_FILE:
        description: Filepath of the *.csproj file, relative to root of repository
        required: true
outputs:
    ASSEMBLY_VERSION:
        description: ReleaseVersion in the *.csproj file
runs:
    using: node12
    main: index.js
    
branding:
    icon: activity
    color: gray-dark
